# Generated by Django 4.2.4 on 2023-08-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksale',
            name='sell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='sold_shares',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
