# Generated by Django 4.2.4 on 2023-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_sales_app', '0003_stocksale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksale',
            name='sold_shares',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
