# Generated by Django 4.2.4 on 2023-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date_bought', models.DateField()),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sell_date', models.DateField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
