# Generated by Django 4.2.4 on 2023-08-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_stock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell_date',
            field=models.DateField(null=True),
        ),
    ]
