# Generated by Django 4.2.4 on 2023-08-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_alter_stock_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
