# Generated by Django 4.2.4 on 2023-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_remove_stock_sell_date_remove_stock_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total_shares',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
