# Generated by Django 4.2.4 on 2023-08-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_app',
            name='estamated_year_income',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='user_app',
            name='filling_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_app',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_app',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='stock_app.stock'),
        ),
    ]
