# Generated by Django 4.2.4 on 2023-08-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_app_estamated_year_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_app',
            name='stocks',
        ),
    ]
