# Generated by Django 4.2.4 on 2023-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_app_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_app',
            name='estamated_year_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
